### PR TITLE
Newsletter field

### PR DESCRIPTION
**Pull request by benbogard**

### CODE REVIEW

**Comment by benbogard** [comment]
As stated previously, I have a successful entry within the PDF table in the database, but no string is being passed. Wondering if it is because when I test, I am also not uploading PDFs which obvs should not be a requirement when adding the field. Pretty sure this is where I am failing to understand things: https://github.com/ihateerrors/520-staging-express/pull/67/commits/e95d577618df3264206bfc3e7bd1cf4369862670

Once I can see the string being added to the database, I can take it from there - the rest I feel confident about - really just need to solve the database entry part. Thanks for your help!

**Comment by ihateerrors** [comment]
Hi @benbogard -- x-posting from other channels, but TL;DR being that the PDF "collection" (Mongoese for what's basically a table in the Cluster, aka DB) is in fact MIME-type controlled because we need to verify that we're sending a document and not just a string to our Azure storage blob, which then generates a URL that's saved in the PDF cluster as a string (we don't store any actual files in Mongo, just strings). 

Hence, we just want to tweak the routes and model so that the info goes to a new collection/table that's not got these controls in place. 

> As stated previously, I have a successful entry within the PDF table in the database, but no string is being passed. Wondering if it is because when I test, I am also not uploading PDFs which obvs should not be a requirement when adding the field. Pretty sure this is where I am failing to understand things: [e95d577](https://github.com/ihateerrors/520-staging-express/commit/e95d577618df3264206bfc3e7bd1cf4369862670)
> 
> Once I can see the string being added to the database, I can take it from there - the rest I feel confident about - really just need to solve the database entry part. Thanks for your help!

**Review by ihateerrors — APPROVED** [review]
Changing the PDF route to include portage-bay-project to render newsletterLInk is great--it's not actually a hack, it just seems like one because "pdf-routes" was just a leftover from when that was the only thing being rendered dynamically on the three program pages. Not worth changing the name at this point, but it works!

**Comment by benbogard** [comment]
> Changing the PDF route to include portage-bay-project to render newsletterLInk is great--it's not actually a hack, it just seems like one because "pdf-routes" was just a leftover from when that was the only thing being rendered dynamically on the three program pages. Not worth changing the name at this point, but it works!

Awesome, thanks for the comfort there - will update my negative language. Thanks again Marguerite!

**Pull request merged**
